version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server
  web:
     build:
        context: ./
        dockerfile: Dockerfile.release
     ports:
       - "80:8080"
     restart: always
     image: sensor_server:dev
     container_name: sensor_server_dev
     env_file:
       - .env
     depends_on:
       - postgres
       - redis
     links:
       - postgres
       - redis
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local